### ISSUE TITLE
libressl v3.4.3/3.5.1 for ffmpeg

### ISSUE THREAD

**Issue by CharlesMengCA** [sfan5/mingw-pkgs#1]
Hi master sfan5.

Sorry for leaving message here like this.

If you have time, could you make ffmpeg to support libressl v3.4.3 or 3.5.1?

libressl v3.1.5 is 2 years old.

Thanks a lot for your work. :)

**Comment by sfan5** [comment]
I don't know why you're asking me but regardless: You can use the `libtls` backend in ffmpeg if you want to use LibreSSL, it works fine even with 3.4.3.
